
package com.video.converter;

import java.awt.Component;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Hunk501
 */
public class MainApp extends javax.swing.JFrame {
    
    private String myfilename, myextension;
    private Converter con;
    
    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        lblIcon.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filechooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnConvert = new javax.swing.JButton();
        btnBrowseSourceFile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFormat = new javax.swing.JComboBox();
        btnBrowseSavePath = new javax.swing.JButton();
        txtSaveLocation = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        txtSourceFile = new javax.swing.JTextField();
        lblIcon = new javax.swing.JLabel();
        progressbar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video Converter v1.0 by liraSoft");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 0, 51));

        jLabel1.setForeground(new java.awt.Color(106, 7, 7));
        jLabel1.setText("Select a File:");

        btnConvert.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnConvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/convert.png"))); // NOI18N
        btnConvert.setText("Convert");
        btnConvert.setToolTipText("Start Convertion process.!");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        btnBrowseSourceFile.setText("Browse..");
        btnBrowseSourceFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseSourceFileActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(106, 7, 7));
        jLabel3.setText("Save to:");

        jLabel2.setForeground(new java.awt.Color(106, 7, 7));
        jLabel2.setText("Format:");

        txtFormat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".mp4", ".avi", ".flv", ".mp3" }));

        btnBrowseSavePath.setText("Browse..");
        btnBrowseSavePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseSavePathActionPerformed(evt);
            }
        });

        txtSaveLocation.setEditable(false);
        txtSaveLocation.setBackground(new java.awt.Color(255, 255, 255));

        lblStatus.setText("Ready.!");

        btnCancel.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("Stop Convertion process.!");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtSourceFile.setEditable(false);
        txtSourceFile.setBackground(new java.awt.Color(255, 255, 255));

        lblIcon.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loader.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSaveLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtSourceFile)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBrowseSavePath, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(btnBrowseSourceFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBrowseSourceFile)
                    .addComponent(txtSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSaveLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseSavePath))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(lblIcon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        progressbar.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(progressbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progressbar, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
        
        Path path = Paths.get("");
        String cur_path = path.toAbsolutePath().toString(); // get the working directory
        //String local_path = System.getProperty("sun.java.command");
        //local_path = local_path.replace("VideoConverter.jar", "");
        String ffmpeg = cur_path + "\\libffmpeg\\ffmpeg.exe";
        //String ffmpeg = "D:\\libffmpeg\\ffmpeg.exe";
        //  Check the ffmpeg.exe location is exists
        File file = new File(ffmpeg);
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, file.getAbsolutePath() +" was not found.!", "Error", JOptionPane.ERROR_MESSAGE);            
        } else {
            if( (txtSourceFile.getText().length() > 0) && (txtSaveLocation.getText().length() > 0) ){
                String filein = txtSourceFile.getText();
                String fileout = txtSaveLocation.getText();
                txtSourceFile.setText(myfilename +"."+ myextension);
                disableGUI();
                btnCancel.setEnabled(true);
                lblStatus.setText("Converting please wait...");
                // start converting..
                con = new Converter(ffmpeg, this, filein, fileout);
                Thread t = new Thread(con);
                t.start();
            } else {
                JOptionPane.showMessageDialog(this, "Some fields must be filled.!", "Error", JOptionPane.ERROR_MESSAGE);            
            }
        }
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnBrowseSourceFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseSourceFileActionPerformed
        // TODO add your handling code here:
        selectFile();
    }//GEN-LAST:event_btnBrowseSourceFileActionPerformed

    private void btnBrowseSavePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseSavePathActionPerformed
        // TODO add your handling code here:
        selectPath();
    }//GEN-LAST:event_btnBrowseSavePathActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        con.cancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainApp m = new MainApp();
                m.setLocationRelativeTo(null);
                m.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseSavePath;
    private javax.swing.JButton btnBrowseSourceFile;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConvert;
    private javax.swing.JFileChooser filechooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JComboBox txtFormat;
    private javax.swing.JTextField txtSaveLocation;
    private javax.swing.JTextField txtSourceFile;
    // End of variables declaration//GEN-END:variables


    
    
    
    private void selectFile(){
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int val = filechooser.showOpenDialog(this);
        if(val == JFileChooser.APPROVE_OPTION){
            myfilename = filechooser.getSelectedFile().getName();
            myfilename = myfilename.replace(".", ":"); // replace '.' from the filename with ':'
            String[] str = myfilename.split(":"); // step through this filename using ':' prefix
            myfilename = str[0]; // get the filename without the file extension ex. .mp4
            myextension = str[1]; // get the extension only ex. .mp4
            txtSourceFile.setText(filechooser.getSelectedFile().getPath());
        }
    }
    
    private void selectPath(){
        filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int val = filechooser.showOpenDialog(this);
        if(val == JFileChooser.APPROVE_OPTION){
            txtSaveLocation.setText(filechooser.getSelectedFile().getAbsolutePath() + "\\"+ myfilename + txtFormat.getSelectedItem().toString());
        }
    }
    
    public void updateStatus(String msg){
        lblStatus.setText(msg);
    }
    
    
    public void disableGUI(){
        Component[] comp = {btnBrowseSavePath, btnBrowseSourceFile, txtSaveLocation, txtSourceFile, txtFormat, btnConvert};
        for(Component c : comp){
            c.setEnabled(false);
        }
        lblIcon.setVisible(true);
    }
    
    public void removeIcon(){
        lblIcon.setVisible(false);
        lblStatus.setText("Ready.!");
    }
    
    public void enableGUI(){
        Component[] comp = {btnBrowseSavePath, btnBrowseSourceFile, txtSaveLocation, txtSourceFile, txtFormat, btnConvert};
        for(Component c : comp){
            c.setEnabled(true);
        }
        lblStatus.setText("Ready.!");
        txtSourceFile.setText("");
        btnCancel.setEnabled(false);
        lblIcon.setVisible(false);
    }
    
    public void updateProgressBar(int val){
        progressbar.setValue(val);
    }

}
